# Generated by Django 5.2.13 on 2026-04-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auditlog_captchalog_notificationlog_otpverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votelog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('vote_attempted', 'Vote Attempt'), ('vote_submitted', 'Vote Submitted'), ('vote_verified', 'Vote Verified'), ('failed_verification', 'Failed Verification'), ('logout', 'User Logout'), ('profile_updated', 'Profile Updated'), ('email_verified', 'Email Verified'), ('2fa_enabled', '2FA Enabled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='votelog',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_logs', to='voting.election'),
        ),
    ]
